version: 2

run:
  timeout: 3m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - revive

linters-settings:
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: indent-error-flow

issues:
  exclude-use-default: false
  max-same-issues: 3